"""empty message

Revision ID: 624849d94e99
Revises: 7bc81c241130
Create Date: 2024-10-05 12:56:42.580607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '624849d94e99'
down_revision = '7bc81c241130'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=300), nullable=False))
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
